---
- name: Collect hardware information with NIC and LLDP details
  hosts: all
  gather_facts: yes
  tasks:
    - name: Install lldpd
      package:
        name:
        - lldpd
        - hwloc-gui
        state: present

    - name: Start lldpd service
      ansible.builtin.service:
        name: lldpd
        state: started

    - name: Create topology png
      ansible.builtin.shell:
        cmd: |
          lstopo --output-format png > /tmp/{{ inventory_hostname }}.png

    - name: Collect NIC models
      command: lshw -class network -json
      register: nic_models

    - name: Collect NIC switch port mapping using LLDP
      command: lldpctl -f json
      register: nic_switch_ports

    - name: Create a dictionary of nic models
      vars:
        models_dict: {}
      set_fact:
        models_dict: "{{ models_dict | combine({item.logicalname: {'nic_model':item.product}}) }}"
      with_items: "{{ nic_models.stdout | from_json }}"

    - name: Create a dictionary of nic switch ports
      vars:
        nic_switch_dict: {}
      set_fact:
        nic_switch_dict: "{{ nic_switch_dict | combine({item.key: {'switch_name':(item.value.chassis.keys() | list)[0], 'switch_port': item.value.port.id.value}}) }}"
      with_dict: "{{ (nic_switch_ports.stdout | from_json).lldp.interface }}"

    - name: merge switch port and nic models
      vars:
        nic_details: {}
      set_fact:
        nic_details: "{{ nic_details | combine({item.key: (item.value | combine(models_dict[item.key]))}) }}"
      with_dict: "{{ nic_switch_dict }}"

    - name: Set disk details
      vars:
        disk_details: {}
      set_fact:
        disk_details: "{{ disk_details | combine({item.key: item.value.size}) }}"
      with_dict: "{{ hostvars[inventory_hostname].ansible_devices }}"

    - name: Assemble all collected information
      set_fact:
        host_info: >-
          {{ inventory_hostname }},
          {{ hostvars[inventory_hostname].ansible_processor_vcpus }},
          {{ hostvars[inventory_hostname].ansible_processor[2] }},
          {{ hostvars[inventory_hostname].ansible_memtotal_mb }},
          {{ nic_details }},
          {{ disk_details }}

    - name: Make sure paths exist
      file:
        state: directory
        path: "{{ image_path | default('images') }}"
      delegate_to: localhost

    - name: Fetch lstopo output
      fetch:
        src: /tmp/{{ inventory_hostname }}.png
        dest: "{{ image_path | default('images') }}/"
        flat: yes

    - name: Append collected information to a CSV
      lineinfile:
        path: "{{ csv_path | default('hardware_info.csv') }}"
        line: "{{ host_info }}"
        create: yes
        insertafter: EOF
      delegate_to: localhost

- name: Add header to CSV
  hosts: localhost
  tasks:
    - name: Add CSV header if it's not already present
      lineinfile:
        path: "{{ csv_path | default('hardware_info.csv') }}"
        line: "Hostname,CPU Cores,CPU Model,RAM,NIC Models and Switch Ports,Disks"
        create: yes
        insertbefore: BOF
        state: present
      delegate_to: localhost
